### ISSUE TITLE
laravel 5.4 call to member function call() on null

### ISSUE THREAD

**Issue by riksnelders** [Vinelab/minion#17]
Fatal error: Uncaught Error: Call to a member function call() on null in C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\laravel\framework\src\Illuminate\Console\Command.php:182
Stack trace:
#0 C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\symfony\console\Command\Command.php(264): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#1 C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\laravel\framework\src\Illuminate\Console\Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#2 C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\symfony\console\Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\symfony\console\Application.php(22 in C:\Users\Caramelo-Rik\ownCloud\Projects\local-dev\dpd\vendor\laravel\framework\src\Illuminate\Console\Command.php on line 182

**Comment by ErrantQuill** [comment]
Could you please show us the contents of the provider class being used here?
